sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t gdury/cinema-users:$TRAVIS_BUILD_NUMBER .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push gdury/cinema-users:$TRAVIS_BUILD_NUMBER;
    fi
